Repository COS301-SE-2022/Intelligent-VMS-Visitor-Management-System-, pull requests merged in 2022-09, with the labels that each got.

#265 Fix/deploy error fix
  backend/libs/auth/src/auth.service.spec.ts
  backend/libs/mail/src/mail.service.spec.ts
  backend/libs/restrictions/src/restrictions.service.spec.ts
  client/components/DownloadChart.jsx
  client/components/LineChart.jsx
  client/components/PieChart.jsx
  client/components/TeamCarousel.jsx
  client/pages/createInvite.jsx
  client/pages/reporting.jsx
  client/pages/visitorDashboard.jsx
  data-prep/app/model.py
Labels: scope:backend:api, scope:backend:service, priority:high, scope:client

#266 Feature/api rate limiter
  backend/libs/auth/src/auth.service.spec.ts
  backend/libs/mail/src/mail.service.int-spec.ts
  backend/libs/parking/src/parking.service.int-spec.ts
  backend/libs/parking/src/parking.service.ts
  backend/libs/receptionist/sign-in/sign-in.service.spec.ts
  backend/libs/receptionist/sign-in/sign-in.service.ts
  backend/libs/receptionist/sign-out/sign-out.service.spec.ts
  backend/libs/receptionist/src/commands/handler/Tray/generateTray.handler.ts
  backend/libs/receptionist/src/models/BSIdata.model.ts
  backend/libs/receptionist/src/models/tray.model.ts
  backend/libs/receptionist/src/receptionist.resolver.ts
  backend/libs/throttler/src/decorators/ratelimit.decorator.ts
  backend/libs/throttler/src/guards/ratelimit.guard.ts
  backend/libs/throttler/src/index.ts
  backend/libs/throttler/src/interfaces/ratelimit-module-options.interface.ts
  backend/libs/throttler/src/interfaces/ratelimit-storage.interface.ts
  backend/libs/throttler/src/providers/ratelimit.provider.ts
  backend/libs/throttler/src/throttler.module.ts
  backend/libs/throttler/src/throttler.service.spec.ts
  backend/libs/throttler/src/throttler.service.ts
  backend/libs/throttler/tsconfig.lib.json
  backend/libs/visitor-invite/src/models/groupInvite.model.ts
  backend/libs/visitor-invite/src/models/invite.model.ts
  backend/libs/visitor-invite/src/visitor-invite.resolver.ts
  backend/libs/visitor-invite/src/visitor-invite.service.int-spec.ts
  backend/nest-cli.json
  backend/package.json
  backend/test/jest-e2e.json
  backend/tsconfig.json
  client/pages/createInvite.jsx
Labels: enhancement, priority:high, scope:client

#267 Fix/prediction key error
  backend/libs/visitor-invite/src/models/predictedInviteData.model.ts
  backend/libs/visitor-invite/src/visitor-invite.service.ts
  backend/src/schema.gql
  client/components/LineChart.jsx
  client/pages/adminDashboard.jsx
  client/pages/reporting.jsx
  data-prep/app/model.py
Labels: enhancement, priority:high, scope:ai

#261 ✨ (VS) : Visitor Suggestion
  backend/libs/visitor-invite/src/models/visitor.model.ts
  backend/libs/visitor-invite/src/queries/handlers/getVisitorVisits.handler.ts
  backend/libs/visitor-invite/src/queries/impl/getVisitorVisits.query.ts
  backend/libs/visitor-invite/src/visitor-invite.module.ts
  backend/libs/visitor-invite/src/visitor-invite.resolver.ts
  backend/libs/visitor-invite/src/visitor-invite.service.ts
  backend/src/schema.gql
  client/components/QRScanner.jsx
  client/components/VisitorSuggestions.jsx
  client/pages/createInvite.jsx
  data-prep/app/tests.ipynb
Labels: enhancement, priority:medium, status: not-ready

#270 ✅(backend): sign-in unit tests
  backend/libs/receptionist/sign-in/sign-in.service.spec.ts
Labels: scope:backend:service, priority:high, scope:tests, status: ready

#269 Updated the curfew time UI
  client/pages/adminDashboard.jsx
Labels: priority:medium

#272 ✅(backend): visitor-invite unit tests
  backend/libs/visitor-invite/src/visitor-invite.service.spec.ts
Labels: scope:backend:service, priority:medium, scope:tests, status: ready

#275 💄 (VS): Show and hide suggestions
  client/components/VisitorSuggestions.jsx
Labels: priority:medium, scope:ui, status: ready

#279 ⚡️ (General): Improve effciency slightly
  data-prep/app/database.py
  data-prep/app/fakeInviteGenerator.py
  data-prep/app/model.py
  data-prep/app/tests.ipynb
Labels: priority:high, status: ready

#280 🐛 (signupErrorMessage) small fix
  client/pages/signUp.jsx
Labels: priority:low

#276 Feature/Face Recognition
  .github/workflows/face-rec-deploy.yml
  backend/libs/auth/src/guards/JwtAuthGuard.guard.ts
  backend/libs/mail/src/mail.service.ts
  backend/libs/parking/src/parking.service.spec.ts
  backend/libs/receptionist/sign-in/sign-in.service.spec.ts
  backend/libs/receptionist/sign-in/sign-in.service.ts
  backend/libs/receptionist/src/receptionist.controller.ts
  backend/libs/receptionist/src/receptionist.module.ts
  backend/libs/receptionist/src/receptionist.resolver.ts
  backend/libs/receptionist/src/receptionist.service.ts
  backend/libs/user/src/guards/httpRoles.guard.ts
  backend/libs/user/src/guards/roles.guard.ts
  backend/libs/visitor-invite/src/queries/handlers/getInviteForSignInData.handler.ts
  backend/libs/visitor-invite/src/queries/impl/getInviteForSignInData.query.ts
  backend/libs/visitor-invite/src/visitor-invite.module.ts
  backend/libs/visitor-invite/src/visitor-invite.resolver.ts
  backend/libs/visitor-invite/src/visitor-invite.service.ts
  backend/package.json
  backend/restrictions.resolver.ts
  backend/src/main.ts
  backend/src/schema.gql
  backend/tsconfig.json
  backend/yarn.lock
  client/'
  client/components/Camera.jsx
  client/components/FaceRec.jsx
  client/components/SignInPopUp.jsx
  client/components/VisitInfoModal.jsx
  client/components/VisitorSuggestions.jsx
  client/components/receptionistSignButton.jsx
  client/lib/camera.lib.js
  client/lib/createGraphQLServer.lib.js
  client/next.config.js
  client/pages/createInvite.jsx
  client/pages/receptionistDashboard.jsx
  face-rec/.dockerignore
  face-rec/.gitignore
  face-rec/Dockerfile
  face-rec/ProcFile
  face-rec/app.py
  face-rec/app/__init__.py
  face-rec/app/classifier/knnClassifier.py
  face-rec/app/database.py
  face-rec/app/faceRec/faceRecLib.py
  face-rec/app/routes.py
  face-rec/model.plk
  face-rec/requirements.txt
  face-rec/testFiles/Person.jpeg
  face-rec/testFiles/Test2.jpg
  face-rec/testFiles/TestImage.jpg
Labels: enhancement, priority:high

#274 ✨ (autoExtension): Create and update cron job on curfew change
  README.md
  backend/libs/parking/src/commands/handlers/removeParkingCommand.handler.ts
  backend/libs/parking/src/parking.service.spec.ts
  backend/libs/receptionist/sign-in/sign-in.service.spec.ts
  backend/libs/receptionist/sign-out/sign-out.service.spec.ts
  backend/libs/receptionist/sign-out/sign-out.service.ts
  backend/libs/receptionist/src/commands/handler/signOutInvite.command.handler.ts
  backend/libs/receptionist/src/commands/impl/signOutInvite.command.ts
  backend/libs/receptionist/src/receptionist.service.spec.ts
  backend/libs/restrictions/src/restrictions.module.ts
  backend/libs/restrictions/src/restrictions.service.spec.ts
  backend/libs/restrictions/src/restrictions.service.ts
  backend/libs/visitor-invite/src/commands/handlers/cancelInvitesCommand.handler.ts
  backend/libs/visitor-invite/src/commands/handlers/extendInvitesCommand.handler.ts
  backend/libs/visitor-invite/src/commands/impl/cancelInvites.command.ts
  backend/libs/visitor-invite/src/commands/impl/extendInvites.command.ts
  backend/libs/visitor-invite/src/models/invite.model.ts
  backend/libs/visitor-invite/src/queries/handlers/getInvitesByDate.handler.ts
  backend/libs/visitor-invite/src/schema/invite.schema.ts
  backend/libs/visitor-invite/src/visitor-invite.module.ts
  backend/libs/visitor-invite/src/visitor-invite.service.int-spec.ts
  backend/libs/visitor-invite/src/visitor-invite.service.spec.ts
  backend/libs/visitor-invite/src/visitor-invite.service.ts
  backend/package.json
  backend/src/app.module.ts
  backend/src/schema.gql
  backend/yarn.lock
  client/components/receptionistSignButton.jsx
  client/pages/receptionistDashboard.jsx
Labels: enhancement, scope:backend:service, status: ready

#282 🐛 (autoExtension): Fix import
  backend/libs/visitor-invite/src/visitor-invite.module.ts
  client/components/receptionistSignButton.jsx
Labels: priority:medium, status: ready

#293 ✅(backend): added user unit tests
  backend/libs/user/src/user.service.spec.ts
Labels: scope:backend:service, priority:medium, scope:tests, status: not-ready

#296 ✅(backend): added throttler unit tests
  backend/libs/throttler/src/throttler.service.spec.ts
Labels: priority:medium, scope:tests, status: ready

#297 ✅ (parking): Remove External Exceptions
  backend/libs/parking/src/parking.service.spec.ts
  backend/libs/parking/src/parking.service.ts
Labels: scope:backend:service, priority:medium, status: ready

#287 Changed signup routing
  backend/libs/auth/src/auth.service.spec.ts
  backend/libs/auth/src/auth.service.ts
  backend/libs/user/src/user.resolver.ts
  backend/src/schema.gql
  client/__tests__/__mocks__/signup.mock.js
  client/__tests__/receptionistSignUp.test.js
  client/__tests__/residentSignUp.test.js
  client/pages/_app.js
  client/pages/receptionist/signUp.jsx
  client/pages/resident/signUp.jsx
  client/pages/signUp.jsx
  client/store/authStore.js
Labels: priority:medium

#284 Origin/feature/admin signup
  backend/libs/auth/src/auth.service.ts
  client/pages/_app.js
  client/pages/adminSignup.jsx
Labels: priority:medium

#300 initialisation page
  client/pages/initialize.jsx
Labels: priority:medium, scope:client

#302 Minor fixes
  client/components/OpenInviteCard.jsx
  client/pages/createInvite.jsx
Labels: priority:low

#306 Backend testing
  backend/libs/auth/src/auth.service.spec.ts
  backend/libs/receptionist/sign-in/sign-in.service.spec.ts
  backend/libs/receptionist/sign-out/sign-out.service.spec.ts
  backend/libs/user/src/user.service.spec.ts
Labels: priority:low

#311 Backend testing
  backend/libs/receptionist/sign-in/sign-in.service.spec.ts
  backend/libs/visitor-invite/src/visitor-invite.service.spec.ts
Labels: priority:low, scope:tests

#317 ✅ (mengelmoeskardoes): A bit of everything
  backend/libs/parking/src/parking.service.spec.ts
  backend/libs/visitor-invite/src/visitor-invite.service.spec.ts
  backend/libs/visitor-invite/src/visitor-invite.service.ts
  data-prep/app/fakeInviteGenerator.py
  data-prep/app/model.py
  data-prep/app/routes.py
Labels: scope:backend:api, scope:backend:service, priority:medium, scope:tests, status: ready
